CREATE TABLE IF NOT EXISTS Student
(
	idStudent INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	surname VARCHAR(50) NOT NULL,
	contact VARCHAR(50) NOT NULL
);
CREATE TABLE IF NOT EXISTS Rate
(
	idRate INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	duration TIME NOT NULL,
	price FLOAT NOT NULL
);
CREATE TABLE IF NOT EXISTS Subject
(
	idSubject INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(50) NOT NULL
);
CREATE TABLE IF NOT EXISTS Lesson
(
	idLesson INT AUTO_INCREMENT PRIMARY KEY,
	idRate INT NOT NULL REFERENCES Rate(idRate),
	idStudent INT NOT NULL REFERENCES Student(idStudent),
	idSubject INT NOT NULL REFERENCES Subject(idSubject),
	lessonN INT DEFAULT 1,
	day DATE NOT NULL,
	startHour TIME NOT NULL,
	duration TIME NOT NULL,
	description VARCHAR(255) NOT NULL
);
CREATE TABLE IF NOT EXISTS Payment
(
	idPayment INT AUTO_INCREMENT PRIMARY KEY,
	day DATE NOT NULL,
	idStudent INT NOT NULL REFERENCES Student(idStudent),
	idRate INT NOT NULL REFERENCES Rate (idRate)
);
CREATE TABLE IF NOT EXISTS Link
(
	idLink INT AUTO_INCREMENT PRIMARY KEY,
	idPayment INT NOT NULL REFERENCES Payment(idPayment),
	idLesson INT NOT NULL UNIQUE REFERENCES Lesson(idLesson)
);